Repository Yapp-17th/Web_2_Backend, pull requests merged in 2020-12, with the labels that each got.

#28 그룹 면접 스터디 api 작성
  src/main/java/com/witherview/database/entity/StudyFeedback.java
  src/main/java/com/witherview/database/entity/StudyRoom.java
  src/main/java/com/witherview/database/repository/StudyRoomParticipantRepository.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/groupPractice/GroupStudyController.java
  src/main/java/com/witherview/groupPractice/GroupStudyDTO.java
  src/main/java/com/witherview/groupPractice/GroupStudyService.java
  src/main/java/com/witherview/groupPractice/exception/AlreadyJoinedStudyRoom.java
  src/main/java/com/witherview/groupPractice/exception/NotFoundStudyRoom.java
  src/main/java/com/witherview/groupPractice/exception/NotJoinedStudyRoom.java
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
  src/test/java/com/witherview/groupPractice/GroupStudySupporter.java
Labels: 🎉feature, 🐎priority:high

#29 혼자연습 등록 버그 수정
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
  src/main/java/com/witherview/video/VideoService.java
Labels: 🐎priority:high, 😱bug, 🚑hotfix

#30 fix(test/study/feedback): 테스트 코드에서도 status code 수정
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
Labels: 🚑hotfix

#31 면접스터디 조회 시 페이징 처리 및 특정 스터디방 조회 api 추가 / 스터디방 참여자 변경 로직 추가
  src/main/java/com/witherview/database/entity/StudyRoom.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/groupPractice/GroupStudyController.java
  src/main/java/com/witherview/groupPractice/GroupStudyDTO.java
  src/main/java/com/witherview/groupPractice/GroupStudyService.java
  src/main/java/com/witherview/groupPractice/exception/AlreadyFullStudyRoom.java
  src/main/java/com/witherview/groupPractice/exception/EmptyStudyRoom.java
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
Labels: 🎉feature, 🐫priority:middle

#32 연습 내역 조회 및 기본 질문 리스트/질문
  src/main/java/com/witherview/account/AccountController.java
  src/main/java/com/witherview/account/AccountDTO.java
  src/main/java/com/witherview/account/AccountService.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
  src/test/java/com/witherview/account/RegisterServiceTest.java
Labels: 🎉feature, 🐫priority:middle

#33 핫픽스..! 인덱스 잘못 참조 수정 및 테케 결과 메세지 수정
  src/main/java/com/witherview/account/AccountService.java
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
Labels: 🚑hotfix

#34 혼자연습 플로우 변경
  src/main/java/com/witherview/database/entity/SelfHistory.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/selfPractice/exception/NotFoundHistory.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryController.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryDTO.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
  src/test/java/com/witherview/selfPractice/HistoryControllerTest.java
  src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
Labels: 🎉feature, 🐎priority:high

#35 Hotfix. 질문 리스트 삭제 안되던 부분 수정
  src/main/java/com/witherview/database/entity/QuestionList.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
Labels: 📚DB, 🚑hotfix

#38 Hotfix. 체크리스트 조회 테스트 코드 버그 수정
  src/test/java/com/witherview/selfPractice/SelfCheckApiTest.java
Labels: 🐎priority:high, 🚑hotfix

#40 Hotfix. 특정 방 참여자 조회할 때 필수 응답 값 빠진 부분 수정
  src/main/java/com/witherview/groupPractice/GroupStudyDTO.java
Labels: 🐎priority:high, 🚑hotfix

#42 음성 인코딩 문제 해결
  src/main/java/com/witherview/video/VideoService.java
Labels: 🐎priority:high, 😱bug, 🚑hotfix

#44 스터디룸 삭제 안되던 오류 해결 및 특정 스터디룸 참가자 조회 시 응답값 추가
  src/main/java/com/witherview/account/AccountService.java
  src/main/java/com/witherview/database/entity/StudyFeedback.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/groupPractice/GroupStudyController.java
  src/main/java/com/witherview/groupPractice/GroupStudyDTO.java
  src/main/java/com/witherview/groupPractice/GroupStudyService.java
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
  src/test/java/com/witherview/groupPractice/GroupStudySupporter.java
Labels: 🐎priority:high, 🚑hotfix

#43 인코딩 작업큐를 통한 인코딩 요청 대응 및 그룹스터디 비디오 등록 API
  src/main/java/com/witherview/database/entity/StudyVideo.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/database/repository/StudyVideoRepository.java
  src/main/java/com/witherview/groupPractice/GroupStudyController.java
  src/main/java/com/witherview/groupPractice/GroupStudyDTO.java
  src/main/java/com/witherview/groupPractice/GroupStudyService.java
  src/main/java/com/witherview/video/EncodingTask.java
  src/main/java/com/witherview/video/EncodingTaskQueue.java
  src/main/java/com/witherview/video/VideoService.java
  src/main/resources/application.yml
  src/test/java/com/witherview/groupPractice/GroupStudyApiTest.java
  src/test/java/com/witherview/selfPractice/HistoryControllerTest.java
Labels: 🎉feature, 🐎priority:high

#45 주/부 관심산업/직무
  src/main/java/com/witherview/account/AccountDTO.java
  src/main/java/com/witherview/account/AccountService.java
  src/main/java/com/witherview/database/entity/User.java
  src/test/java/com/witherview/account/LoginControllerTest.java
  src/test/java/com/witherview/account/RegisterControllerTest.java
  src/test/java/com/witherview/account/RegisterServiceTest.java
  src/test/java/com/witherview/groupPractice/GroupStudySupporter.java
  src/test/java/com/witherview/selfPractice/HistoryControllerTest.java
  src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
Labels: 🎉feature, 🐫priority:middle
