Repository Yapp-17th/Web_2_Backend, pull requests merged in 2020-11, with the labels that each got.

#8 엔티티/예외처리/회원가입
  src/main/java/com/witherview/account/AccountController.java
  src/main/java/com/witherview/account/AccountDTO.java
  src/main/java/com/witherview/account/AccountService.java
  src/main/java/com/witherview/account/exception/DuplicateEmail.java
  src/main/java/com/witherview/account/exception/NotEqualPassword.java
  src/main/java/com/witherview/configuration/WebConfig.java
  src/main/java/com/witherview/database/entity/SelfStudy.java
  src/main/java/com/witherview/database/entity/StudyFeedback.java
  src/main/java/com/witherview/database/entity/StudyRoom.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/database/repository/SelfStudyRepository.java
  src/main/java/com/witherview/database/repository/UserRepository.java
  src/main/java/com/witherview/exception/BusinessException.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/exception/ErrorResponse.java
  src/main/java/com/witherview/exception/GlobalRestExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/witherview/WitherviewApplicationTests.java
  src/test/java/com/witherview/account/AccountControllerTest.java
  src/test/java/com/witherview/support/MockMvcSupporter.java
  src/test/java/com/witherview/support/TestSupporter.java
Labels: 🎉feature, 🐎priority:high, 📚DB

#11 혼자연습하기 - 질문/질문리스트 api 작성
  src/main/java/com/witherview/database/entity/Question.java
  src/main/java/com/witherview/database/entity/QuestionList.java
  src/main/java/com/witherview/database/repository/QuestionListRepository.java
  src/main/java/com/witherview/database/repository/QuestionRepository.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/selfPractice/CustomValidator.java
  src/main/java/com/witherview/selfPractice/Question/SelfQuestionApiController.java
  src/main/java/com/witherview/selfPractice/Question/SelfQuestionDTO.java
  src/main/java/com/witherview/selfPractice/Question/SelfQuestionService.java
  src/main/java/com/witherview/selfPractice/QuestionList/SelfQuestionListApiController.java
  src/main/java/com/witherview/selfPractice/QuestionList/SelfQuestionListDTO.java
  src/main/java/com/witherview/selfPractice/QuestionList/SelfQuestionListService.java
  src/main/java/com/witherview/selfPractice/exception/NotFoundQuestion.java
  src/main/java/com/witherview/selfPractice/exception/NotFoundQuestionList.java
  src/main/java/com/witherview/selfPractice/exception/NotFoundUser.java
  src/test/java/com/witherview/selfPractice/SelfQuestionApiTest.java
  src/test/java/com/witherview/selfPractice/SelfQuestionListApiTest.java
Labels: 🎉feature

#12 로그인
  src/main/java/com/witherview/account/AccountController.java
  src/main/java/com/witherview/account/AccountDTO.java
  src/main/java/com/witherview/account/AccountService.java
  src/main/java/com/witherview/account/AccountSession.java
  src/main/java/com/witherview/account/exception/InvalidLogin.java
  src/main/java/com/witherview/configuration/InterceptorConfig.java
  src/main/java/com/witherview/configuration/WebConfig.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/exception/GlobalRestExceptionHandler.java
  src/main/java/com/witherview/interceptor/AuthInterceptor.java
  src/main/resources/application.yml
  src/test/java/com/witherview/account/AccountSupporter.java
  src/test/java/com/witherview/account/LoginControllerTest.java
  src/test/java/com/witherview/account/RegisterControllerTest.java
Labels: 🎉feature, 🐎priority:high

#15 혼자연습 내역 등록/조회 API
  src/main/java/com/witherview/configuration/SwaggerConfig.java
  src/main/java/com/witherview/database/entity/Question.java
  src/main/java/com/witherview/database/entity/QuestionList.java
  src/main/java/com/witherview/database/entity/SelfHistory.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/database/repository/SelfHistoryRepository.java
  src/main/java/com/witherview/database/repository/SelfStudyRepository.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryController.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryDTO.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
  src/main/resources/application.yml
  src/test/java/com/witherview/account/LoginControllerTest.java
  src/test/java/com/witherview/account/RegisterControllerTest.java
  src/test/java/com/witherview/selfPractice/HistoryControllerTest.java
  src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
  src/test/java/com/witherview/selfPractice/SelfQuestionApiTest.java
  src/test/java/com/witherview/selfPractice/SelfQuestionListApiTest.java
Labels: 🎉feature, 🐫priority:middle, 🚑hotfix

#16 CORS
  src/main/java/com/witherview/configuration/WebConfig.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryController.java
Labels: 🐎priority:high, 🚑hotfix

#26 질문 저장/수정 시 날짜 정보 들어가도록 수정
  src/main/java/com/witherview/WitherviewApplication.java
  src/main/java/com/witherview/database/entity/CreatedBaseEntity.java
  src/main/java/com/witherview/database/entity/Question.java
  src/main/java/com/witherview/database/entity/User.java
  src/main/java/com/witherview/selfPractice/Question/SelfQuestionApiController.java
  src/main/java/com/witherview/selfPractice/Question/SelfQuestionDTO.java
Labels: 🐫priority:middle, 📚DB

#27 영상 업로드 및 HLS 변환 + 리소스 접근
  build.gradle
  src/main/java/com/witherview/configuration/InterceptorConfig.java
  src/main/java/com/witherview/configuration/WebConfig.java
  src/main/java/com/witherview/database/entity/SelfHistory.java
  src/main/java/com/witherview/exception/ErrorCode.java
  src/main/java/com/witherview/interceptor/ResourceAuthInterceptor.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryController.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryDTO.java
  src/main/java/com/witherview/selfPractice/history/SelfHistoryService.java
  src/main/java/com/witherview/video/VideoService.java
  src/main/java/com/witherview/video/exception/NotSavedVideo.java
  src/main/resources/application.yml
  src/test/java/com/witherview/selfPractice/HistoryControllerTest.java
Labels: 🎉feature, 🐎priority:high, 🤫security
